### ISSUE TITLE
minor makefile tuning

### ISSUE THREAD

**Issue by mulderp** [ezaquarii/bison-flex-cpp-example#1]
hello,

this is quite nice to get going with cpp and parsing things.
small comment, I had to tell my Makefile where to find my bison and boost on Mac OS. So, I added this:

``` cpp
bison=/usr/local/opt/bison/bin/bison

all:
    flex -o scanner.cpp scanner.l
    $(bison) -o parser.cpp parser.y
    g++ -I/usr/local/opt/boost/include -g main.cpp scanner.cpp parser.cpp interpreter.cpp command.cpp -o a.out
```

**Comment by iobtoolkit** [comment]
bison should be found in your ${PATH}, not hardcoded into Makefile.

It is a well established practice to supply library includes directories using environment variables. I see that you hardcoded path to boost.

**Comment by mulderp** [comment]
ok, thanks for your suggestions, I'll follow these.
