### ISSUE TITLE
boost requirement ? 

### ISSUE THREAD

**Issue by dridk** [ezaquarii/bison-flex-cpp-example#2]
➜  bison-flex-cpp-example git:(master) make
flex -o scanner.cpp scanner.l
bison -o parser.cpp parser.y
g++ -g main.cpp scanner.cpp parser.cpp interpreter.cpp command.cpp -o a.out
interpreter.cpp:33:35: fatal error: boost/concept_check.hpp: Aucun fichier ou dossier de ce type
compilation terminated.
Makefile:2 : la recette pour la cible « all » a échouée
make: *** [all] Erreur 1

interpreter.cpp:33:35: fatal error: boost/concept_check.hpp: Aucun fichier ou dossier de ce type

**Comment by ezaquarii** [comment]
Le problème est résolu. Merci.
